### ISSUE TITLE
Doesn't appear to be working...?

### ISSUE THREAD

**Issue by Wowfunhappy** [Exormeter/AlarmFade#1]
Hello!

I love the idea behind this tweak! It's *very* annoying how Apple couples alarm volume with ringer volume. The fade in is a nice touch.

However, it doesn't seem to be working at all for me? When I set the ringer volume to the lowest setting and play an alarm, the alarm is very quiet, even with fade in turned off. If I turn on fade in and wait, the volume never increases.

I'm on a 6S running 12.1.1.

Is there something I'm doing wrong? I don't think I'm the only one having trouble, unfortunately. If you look at TweakCompatible, three people reported the tweak as not working on 12.1.1, even though that's a supported version.

Can you please look into this? Thank you so much! And, let me know if I'm just doing something really stupid...

**Comment by Exormeter** [comment]
If you set the volume to the lowest setting it won’t fade, because the end volume is already reached. The slider sets the maximum volume to which you want the volume increased.

Please try it again and report you finding. I‘m on 12.1.2, so it is hard to replicate issues on lower iOS versions.

Did you had AlarmVolume installed on your phone? If yes, could you remove the prefs and test it again?
One tester said that this worked for him: https://www.reddit.com/r/jailbreak/comments/b06cv6/release_alarmfade_for_ios12/eiev2mu

Edit: Please remove AlamVolume completely, it’s not compatible with my tweak.

**Comment by Wowfunhappy** [comment]
AlarmVolume has never been installed, unfortunately. 

Alarmfade’s volume is all the way up, but the ringer volume is turned down, and the phone’s alarm is only playing at the phone’s (low) volume, even after waiting for the fade in.

**Comment by Exormeter** [comment]
I have found a bug where the preferences aren't created when you install the tweak. Could you tell me whats written in /private/var/mobile/Library/preferences/com.exormeter.alarmfade.plist ?

**Comment by Wowfunhappy** [comment]
The file exists on my phone. It's contents is below:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fadeIsEnabled</key>
	<true/>
	<key>fadein</key>
	<string>10</string>
	<key>maxVolume</key>
	<real>0.99000000953674316</real>
</dict>
</plist>
```

**Comment by Exormeter** [comment]
That is what I expected. The problem is/was that I did't know that the preferences are only put into the pref file when they are changed in the settings. So when you install the tweak, the file doesn't exist and the tweak thinks it is not enabled. 

If you disable the tweak in the settings and the enable it again it should work. Please try that and tell me if it worked. 

I already pushed an updated that has the default settings in the tweak itself.

**Comment by Wowfunhappy** [comment]
Confirming that worked, thank you!
